display_name: 天阙

packager: chen08209
packagerEmail: chen08209@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: TianQue

group: Applications/Internet

startup_notify: true